version: '3'

services:

  php-fpm:
    build:
      context: ./php-fpm
    container_name: pay_task_php
    volumes:
      - ../:/var/www/pay_test_task
    tty: true

  nginx:
    image: nginx:1.19.3
    container_name: pay_task_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../:/var/www/pay_test_task
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443

  mysql:
    image: mysql/mysql-server:8.0.22
    container_name: pay_task_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
